<a href="https://colab.research.google.com/github/hhaemin/my-repository/blob/main/Class_04_numpy_4_vector_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### inner product

In [ ]:
import numpy as np
a = np.random.randint(0,10,(2,4))
b = np.random.randint(0,10,(2,4))
a,b

(array([[0, 7, 2, 3],
        [5, 6, 1, 4]]), array([[5, 2, 4, 6],
        [6, 4, 3, 1]]))

In [ ]:
np.dot(a,b.T)

array([[40, 37],
       [65, 61]])

In [ ]:
np.inner(a,b)

array([[40, 37],
       [65, 61]])

 - numpy.inner : 1차원 또는 2차원 배열일 경우 내적을 위해 두 번째 행렬을 전치한 다음 곱해준다.
 - numpy.dot : 2차원 배열의 경우 행렬곱 연산을 수행하며 1차원 배열일 경우 벡터의 내적에 해당한다. 

In [ ]:
np.inner(a,b.T)

ValueError: ignored

### 고유값, 고유벡터

In [ ]:
a = np.array([[1,-1], [1,1]])

In [ ]:
value, vector = np.linalg.eig(a)
value, vector

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [ ]:
arr = np.random.randn(3,3)
arr

array([[ 0.55501609, -0.20365391,  1.2035725 ],
       [ 0.26968391,  0.43470709,  0.50179806],
       [ 1.59190176,  0.38258144,  0.24218151]])

In [ ]:
mat = np.dot(arr.T, arr)
mat, np.linalg.inv(mat)

(array([[2.91492348, 0.61323437, 1.18885814],
        [0.61323437, 0.37681372, 0.06567708],
        [1.18885814, 0.06567708, 1.75903995]]),
 array([[ 0.80188672, -1.21847488, -0.49646609],
        [-1.21847488,  4.52269926,  0.65465035],
        [-0.49646609,  0.65465035,  0.87958903]]))

In [ ]:
np.dot(mat, np.linalg.inv(mat))

array([[ 1.00000000e+00, -1.82303507e-17,  2.18944198e-16],
       [-6.07843501e-17,  1.00000000e+00, -2.24726212e-17],
       [ 5.31664211e-17, -1.95076743e-16,  1.00000000e+00]])